# Generated by Django 3.0.3 on 2021-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_Details',
            },
        ),
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Dob', models.CharField(default=None, max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.IntegerField(default=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Speciality', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Doctor_Details',
            },
        ),
        migrations.CreateModel(
            name='Feedback_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(default=None, max_length=100)),
                ('Uid', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'Feedback_details',
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Smoking', models.CharField(default=None, max_length=100)),
                ('QuidChewing', models.CharField(default=None, max_length=100)),
                ('Alcohol', models.CharField(default=None, max_length=100)),
                ('DifficultyInChewing', models.CharField(default=None, max_length=100)),
                ('PainlessUlceration', models.CharField(default=None, max_length=100)),
                ('NeckLump', models.CharField(default=None, max_length=100)),
                ('LossOfApetite', models.CharField(default=None, max_length=100)),
                ('LossOfWeight', models.CharField(default=None, max_length=100)),
                ('HoarsenessOfVoice', models.CharField(default=None, max_length=100)),
                ('Bleeding', models.CharField(default=None, max_length=100)),
                ('BurningSensationInTheMouth', models.CharField(default=None, max_length=100)),
                ('Painful', models.CharField(default=None, max_length=100)),
                ('Swelling', models.CharField(default=None, max_length=100)),
                ('Numbness', models.CharField(default=None, max_length=100)),
                ('Result', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'TrainingData',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Dob', models.CharField(default=None, max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.IntegerField(default=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
