# Generated by Django 3.0.3 on 2021-03-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdata',
            old_name='Alcohol',
            new_name='BreathingIssue',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='Bleeding',
            new_name='DifficultyInDailyActivity',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='BurningSensationInTheMouth',
            new_name='DifficultyInSwalling',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='DifficultyInChewing',
            new_name='Drowsiness',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='HoarsenessOfVoice',
            new_name='Fatique',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='LossOfApetite',
            new_name='Headache',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='LossOfWeight',
            new_name='HearingIssue',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='NeckLump',
            new_name='LossInVision',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='Numbness',
            new_name='MemoryProblem',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='Painful',
            new_name='Nausea',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='PainlessUlceration',
            new_name='ProblemInDailyActivity',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='QuidChewing',
            new_name='Seizures',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='Smoking',
            new_name='SleepProblem',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='Swelling',
            new_name='Vomiting',
        ),
    ]
