# Generated by Django 3.0.3 on 2021-03-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBrain', '0002_auto_20210323_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdata',
            old_name='DifficultyInDailyActivity',
            new_name='DifficultyInFineMotorSkills',
        ),
    ]
